import {PublicImage} from './public-image';
import {StolenRecord} from './stolen-record';

export interface BikeFull {
  date_stolen: number;
  description: string | null;
  frame_colors: string[];
  frame_model: string;
  id: number;
  is_stock_img: boolean;
  large_img: string;
  location_found: string | null;
  manufacturer_name: string;
  external_id: number | null;
  registry_name: string | null;
  registry_url: string | null;
  serial: string;
  status: string;
  stolen: boolean;
  stolen_coordinates: number[];
  stolen_location: string;
  thumb: string;
  title: string;
  url: string;
  year: number;
  propulsion_type_slug: string;
  cycle_type_slug: string;
  registration_created_at: number;
  registration_updated_at: number;
  api_url: string;
  manufacturer_id: number;
  paint_description: string | null;
  name: string | null;
  frame_size: string | null;
  rear_tire_narrow: boolean;
  front_tire_narrow: string | null;
  type_of_cycle: string;
  test_bike: boolean;
  rear_wheel_size_iso_bsd: string | null;
  front_wheel_size_iso_bsd: string | null;
  handlebar_type_slug: string | null;
  frame_material_slug: string | null;
  front_gear_type_slug: string | null;
  rear_gear_type_slug: string | null;
  extra_registration_number: number | null;
  additional_registration: string | null;
  stolen_record: StolenRecord;
  public_images: PublicImage[];
  components: unknown;
}
